# AUTOGENERATED! DO NOT EDIT! File to edit: ..\04_cli.ipynb.

# %% auto 0
__all__ = ['rough']

# %% ..\04_cli.ipynb 4
@call_parse
def rough(
    fname:str   = None, # File name or glob to be read
    delim:str   = '', #Delimeter for the file '' for txt, ',' for .csv etc.
    result:str  = None, #Folder to write results to, if not set, writes to 'results' folder
    
    level:bool  = True, #Perform plane levelling 
    form:bool   = True, #Remove form by polynomial subtraction
    deg:int     = 3, #Degree of polynomial to remove
    smooth:bool = True, #Smooth the array by applying a gaussian
    sigma:int   = 1, #Sigma for gaussian to be applied
    
    gen_rot:bool= True, #Generate rotational profiles and apply parameter calculation to them
    
    section:bool= True, #Generate sections
    sec_how:str = 'square', #Type of section to generate, currently only supports 'square'
    sec_num:int = 100, #Number of sections to generate
    
    params1D:list = [Ra,Rms,Rku,Rsk], # list of 1D parameters to calculate,
    params2D:list = [Sa,Sms,Sku,Ssk] #list of 2D parameters to calculate
):
    for file in fname:
        array = np.loadtxt(fname,delimeter=delim)
        
        if level:
            array = plane_level(array)
        if form:
            array = remove_form(array)
        if smooth:
            array = smooth_image(array,sigma=sigma)
        if gen_rot:
            profiles = gen_rot_profs(array)
            #Helper function that computes parameters
        if section:
            sections = gen_sections(array, how=sec_how, number = sec_num)
            #Helper function that computes parameters
            section_results = None
            result_f = result + '/' + file + '_section' + ('.csv' if delim == ',' else '.txt')
            np.savetxt(result_f, section_results, delim =delim) #Save the section results
        
        
        
        

