# AUTOGENERATED! DO NOT EDIT! File to edit: ..\01_profile.ipynb.

# %% auto 0
__all__ = ['Ra', 'Rms']

# %% ..\01_profile.ipynb 4
import numpy as np
from PIL import Image  

# %% ..\01_profile.ipynb 5
def Ra(im, #Numpy array or arraylike
       axis = 0, 
       norm = True #Normalize the profile by subtracting the mean 
      ):
    '''
    Calculates Mean Absolute Roughness (Ra) along given axis. Defined as the average deviation of absolute height values from the mean line.
    '''
    if norm:
        im = im - np.mean(im, axis = axis)
    return np.mean(np.absolute(im), axis = axis)

# %% ..\01_profile.ipynb 8
def Rms(im, #Numpy array or array like
        axis = 0, 
        norm = True #Normalize the profile by subtracting the mean
       ):
    '''
    Calculates Root Mean Square Roughness (Rms) along given axis. Defined as the root mean square of deviations of height from the mean line of a given profile. 
    '''
    if norm:
        im = im - np.mean(im, axis = axis)
    return np.sqrt(np.mean(np.square(im), axis = axis))
