# AUTOGENERATED! DO NOT EDIT! File to edit: ..\02_section.ipynb.

# %% auto 0
__all__ = ['Sa']

# %% ..\02_section.ipynb 3
def Sa(im, #Numpy array or arraylike
       norm = True #Normalize the section by subtracting the mean
      ):
    if norm:
        im = im - np.mean(im, axis = None)
    return np.mean(np.absolute(im), axis = None)
