# AUTOGENERATED! DO NOT EDIT! File to edit: ..\02_section.ipynb.

# %% auto 0
__all__ = ['Sa', 'Sms']

# %% ..\02_section.ipynb 3
from .data import *
from .profile import *

# %% ..\02_section.ipynb 4
def Sa(im, #Numpy array or arraylike
       norm = True #Normalize the section by subtracting the mean
      ):
    '''
    Calculates the mean absolute difference from the mean plane. Equivalent to Ra(array, axis = None)
    '''
    if norm:
        im = im - np.mean(im, axis = None)
    return np.mean(np.absolute(im), axis = None)

# %% ..\02_section.ipynb 5
def Sms(im, #Numpy array or arraylike
        norm = True #Normalize the section by subtracting the mean
       ):
    '''
    Calculates the root mean square difference from the mean plane. Equivalent to Rms(array, axis = None)
    '''
    if norm:
        im = im - np.mean(im, axis = None)
    return np.sqrt(np.mean(np.square(im), axis = None))
