# AUTOGENERATED! DO NOT EDIT! File to edit: ..\02_section.ipynb.

# %% auto 0
__all__ = ['Sa', 'Sms', 'Ssk', 'Sku']

# %% ..\02_section.ipynb 3
from .data import *
from .profile import *

import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import skew, kurtosis
from scipy.signal import find_peaks

# %% ..\02_section.ipynb 6
def Sa(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sa of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
      ):
    '''
    Calculates the mean absolute difference from the mean plane. Equivalent to Ra(array, axis = None)
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims=True)
        
    return np.mean(np.absolute(im), axis = axis)

# %% ..\02_section.ipynb 8
def Sms(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sms of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the root mean square difference from the mean plane. Equivalent to Rms(array, axis = None)
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)

    return np.sqrt(np.mean(np.square(im), axis = axis))

# %% ..\02_section.ipynb 10
def Ssk(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Ssk of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the Skew of the section. Equivalent to Rsk(im, axis = None) for an (m,n) array
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)
     
    return skew(a = im, axis=axis, **kwargs)
        
        

# %% ..\02_section.ipynb 12
def Sku(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sku of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the Kurtosis of the section. Equivalent to Rku(im, axis = None) for an (m,n) array
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)
     
    return kurtosis(a = im, axis=axis, **kwargs)
